service: serverless-multicloud-nodejs
provider:
  name: google
  runtime: nodejs10
  region: us-central1
  project: pagotto-learn
  credentials: C:\Users\renic\.gcloud\serverless-keyfile.json
plugins:
  - serverless-google-cloudfunctions
  - serverless-express
package:
  exclude:
    - .gitignore
    - .git/**
functions:
  app:
    handler: handler
    events:
      - http: path