service: serverless-multicloud-nodejs
provider:
  name: azure
  region: West US 2
  runtime: nodejs10
plugins:
  - serverless-azure-functions
  - serverless-express
package:
  exclude:
    - local.settings.json
    - .gitignore
    - .git/**
functions:
  tdc:
    handler: handler.handler
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
          name: req
          methods:
            - get
      - http: true
        x-azure-settings:
          direction: out
          name: res